- src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
- src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
- src/main/resources/application.properties
기존 동작 방싱
- 메인 페이지에서 데스크테리어 생성 버튼을 누르면 사용자의 남은 토큰 횟수를 확인한다.
- 토큰이 남아있으면 이미지 업로드 페이지로 이동하고 그렇지 않으면 "오늘은 더이상 이미지 생성을 할 수 없어요" 모달이 출력된다.
개선 동작 방식
- 메인 페이지에서 데스크테리어 생성 버튼을 누르면 이미지 업로드 페이지로 이동한다.
- 사용자의 남은 토큰 횟수를 화면에 출력한다.
- 남은 토큰 수가 0일 경우, 이미지 업로드를 하더라도 이미지 생성 버튼이 비활성화 된다.
> 설명: 기능이 잘 동작하는지 로컬에서 확인할 수 있는 절차를 기술합니다.
1. IntelliJ 상단에 서버 실행 버튼을 클릭한다.
2. 로그인 후 메인페이지의 데스크 테리어 생성 버튼을 클릭한다.
3. 자신의 토큰을 확인하고 이미지를 업로드 후 버튼 활성 상태를 확인한다.
> fix: 메인 페이지에서 사용자의 이미지 생성 토큰 로직 수정

- src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductDomainServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/reply/application/serviceImpl/ReplyServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
- Service 클래스의 메서드에서 @Transactional 설정을 추가하거나 재설정한다.
- 읽기 전용 메서드는 readOnly=true를 추가하여 쓰기 작업에 대한 예외 감지를 처리한다.
> fix: Service 클래스 @Transactional 추가 및 재설정

- .github/workflows/docker-deploy.yml
docker 실행 시
`--logging.file.path=/logs/backend.log`
와 같이 설정하면 
/logs/backend.log/spring.log 에 로그가 저장됩니다. 그래서 의도한 것 처럼 로그 수집이 불가능합니다.
그래서
`--logging.file.name=/logs/backend.log`
와 같이 변경했습니다.
> fix: 로그 경로가 아니라 파일명 기준으로 실행하도록 변경

- src/test/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImplTest.java
- LikeServiceImplTest.java에서 User, Post에 대한 값 존재하지 않을 경우 예외 처리 되는 테스트 코드 추가
- 좋아요 또는 취소 시 해당 사용자 및 게시글 정보 존재하지 않을 경우 NOT_FOUND 예외 테스트 코드 작성
- LikeServiceImplTest.java에서 'ctrl + F10' 또는 커버리지로 테스트 코드 실행
> feat: User, Post에 대한 값 존재 유무에 따른 테스트 코드 추가

- src/main/java/com/kakaotech/ott/ott/productOrder/application/service/ProductOrderService.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
- src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/entity/ProductOrderEntity.java
- src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/presentation/controller/ProductOrderController.java
- 주문 취소 기능 개발
- Soft delete 적용
- ProductOrder의 deleteAt null -> now() 적용
1. IDE 서버 실행  
2. Postman에서 `DELETE /api/v1/orders/{orderId}` 호출  
3. 'POST /api/v1/orders/{orderId}' 호출하여 조회되는지 확인
> feat: 주문 취소 기능 개발(Soft Delete)

- src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/component/OrderConfirmBatchJob.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/service/ProductOrderService.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrder.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderJpaRepository.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
- src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/entity/ProductOrderEntity.java
- src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/presentation/controller/ProductOrderController.java
- 주문 구매 확정 기능 개발
- 사용자 직접 입력, 설정 기간 후 자동 처리(배치)
- 매일 자정 자동 배치 처리 작동
1. IDE 서버 실행  
2. Postman에서 `POST /api/v1/orders/{orderId}/confirm` 호출  
3. 'DELIVERED' 상태에서만 주문 확정이 되는지 확인
4. 매일 자정 자동 배치 처리 되는지 확인
> feat: 주문 구매 확정 기능 개발(사용자 직접 입력, 자동 구매 확정)

- src/main/java/com/kakaotech/ott/ott/productOrder/application/service/ProductOrderService.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrder.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrderStatus.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
- src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/entity/ProductOrderEntity.java
- src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/presentation/controller/ProductOrderController.java
- src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/response/ProductOrderConfirmResponseDto.java
- src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/response/ProductOrderResponseDto.java
- 주문 확정 시 응답 dto 추가
- orderId, status 응답=
1. IDE 서버 실행  
2. Postman에서 `POST /api/v1/orders/{orderId}/confirm` 호출
> feat: 주문 확정 dto 추가

- src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/service/ProductOrderService.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrder.java
- src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
- src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/presentation/controller/ProductOrderController.java
- 주문 취소와 주문 내역 삭제의 기능을 분리
- 주문 취소는 status를 PAID -> CANCEL로 변경, 주문 내역 삭제는 deleted_at 값 활성화(Soft delete)
1. IDE 서버 실행  
2. Postman에서 `POST /api/v1/orders/{orderId}` 호출  
3. 'status' 변경 확인
> feat: 주문 취소와 내역 취소 기능 분리

- src/main/java/com/kakaotech/ott/ott/aiImage/domain/model/ImageGenerationHistory.java
- src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/ImageGenerationHistoryJpaRepository.java
- src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/ImageGenerationHistoryRepository.java
- src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/entity/ImageGenerationHistoryEntity.java
- src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/ImageGenerationHistoryRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
- 이미지 생성 가능 토큰 수 1개 -> 3개로 수정
- 이미지 생성 내역을 관리하는 ImageGenerationHistory 테이블 추가
- 금일 날짜(이미지를 생성하는 일자)와 user_id에 해당하는 row값 계산 후 생성 가능한 토큰 수 반환
> feat: 이미지 생성 가능 토큰수 수정

- src/main/java/com/kakaotech/ott/ott/aiImage/application/service/AiImageService.java
- src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/aiImage/domain/model/AiImageConcept.java
- src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/response/AiImageResponseDto.java
- src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/MyDeskImageResponseDto.java
- 기존 : 나의 데스크 조회 시 before + after 이미지 조회
- 수정 : after 또는 before 이미지 클릭 시 해당 이미지의 추천 상품 리스트 조회 페이지 이동
> feat: 나의 데스크 조회에서 상세 페이지 이동 추가

- src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItem.java
- src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItemStatus.java
- src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemJpaRepository.java
- src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemRepository.java
- src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/entity/OrderItemEntity.java
- src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/repositoryImpl/OrderItemRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/request/ServiceProductDto.java
- src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/response/MyProductOrderResponseDto.java
- 기존 OrderItem 에서 어떤 특가 상태로 구매한 것인지 확인 불가능
- promotion_id를 주입 받아 어떤 특가 상태에서 구매했는지 확인
- 기존 상품가, 할인금액으로만 관리하여 최종 가에 대해서 추가적인 계산 필요
- 정상가, 할인 금액, 최종가를 분리하여  명시적인 가격 상태 관리
- 컬럼이 바뀜에 따라 응답 dto 변경
> feat: OrderItems 특가 상태, 정상가, 할인금액, 최종가 추가 및 분리 후 Dto 변경

- src/main/java/com/kakaotech/ott/ott/recommendProduct/application/serviceImpl/DeskProductServiceImpl.java
- 추천 제품 목록 및 상세 조회 시 해당 사용자의 정보 조회 로직 제거
- 정보 조회한다면 security에서 모든 사용자 허용하더라도 user_id가 null인 사용자를 조회하므로 예외 발생
> fix: 추천 제품 조회 시 해당 사용자 정보 조회 제거

- src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
- src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/user/domain/model/User.java
- 서비스 상품 주문 요청 시 사용자의 is_verified 확인 후 응답
- 카테부 회원 인증 메서드 도메인 로직에 추가
- USER_NOT_VERIFIED 예외 문구 변경
> feat: 상품 주문 요청 시 카테부 인증 회원 확인

- src/main/java/com/kakaotech/ott/ott/recommendProduct/application/serviceImpl/ProductDomainServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/AiImageRecommendedProductJpaRepsitory.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/DeskProductJpaRepository.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/DeskProductRepository.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/infrastructure/repositoryImpl/AiImageRecommendedProductRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/infrastructure/repositoryImpl/DeskProductRepositoryImpl.java
- 추천 상품에 대해서 product_code가 UNIQUE 처리 되어 있어, 동일한 제품이 이미지 생성하며 들어올 경우 대비하지 않음
- 만약 해당 추천 상품이 이미 존재한다면 해당 상품 id값을 매핑
> fix: 추천 상품 중복 저장 충돌 해결

- src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
- src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java
- 첫 페이지 조회 시 lastPostId null로 입력
- JPQL에서 lastPostId = null 처리 코드단에서 처리
- 첫번째 조회와 그 후 조회 분기 처리
> feat: 게시글 페이지네이션 lastPostId null 분기 처리

- src/main/java/com/kakaotech/ott/ott/OttApplication.java
- src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/AiImageRecommendedProductJpaRepsitory.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/AiImageRecommendedProductRepository.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/infrastructure/repositoryImpl/AiImageRecommendedProductRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/presentation/dto/response/RecommendedProductProjection.java
- 생성된 AI 이미지 조회 시 이미지 기반으로 생성된 제품 당 스크랩 여부를 각각 조회
- 즉 추천 상품이 N개일 때, 스크랩 여부 N번 조회
- 기존 쿼리 사용자 조회(1회) + 이미지 조회(1회) + 추천 목록 조회(1회) + 상품에 대한 스크랩 여부 조회(N번) = 18회 이상 조회
- DTO Projection으로 필요한 컬럼 한 번에 조회
- 수정 후 사용자 조회(1회) + 이미지 조회(1회) + 상품과 스크랩 여부 조회(1회) = 3회
> feat: AiImage 조회 N+1 문제 해결

- src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductVariantQueryRepository.java
- src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductVariantQueryRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductVariantRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/ProductListResponseDto.java
- src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapQueryRepository.java
- src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/repositoryImpl/ScrapQueryRepositoryImpl.java
- 서비스 상품 목록 페이지 queryDSL 적용
- 총 3단계 과정
- 첫번째 단계 : queryDSL 미적용
- 두번째 단계 : queryDSL 적용
- 세번째 단계 : queryDSL 적용 + 이미지 가져오기 최적화 + distinct 적용
- 평균 응답 시간 2.4초 -> 1.3초 -> 0.8초
- 최대 응답 시간 9.5초 -> 5.3초 -> 4.5초
- 처리량 30.9 req/sec -> 54.8 req/sec -> 88 req/sec
> feat: 서비스 상품 목록 페이지 queryDSL 적용

- src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductVariantQueryRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/ProductListResponseDto.java
- 기존 특가 상품과 연결되어 있는 상품이 특가 상태가 끝나도 일반 상품에서 보이지 않는 현상 발생
- 코드 확인 후 variant과 promotion이 연결되어 있는 것을 특가 상태로 인식하고 있는 것을 확인(is_on_promotion이 아닌 관계 형성을 특가 상태로 판단)
- 해당 내용을 is_on_promotion으로 판단하도록 로직 변경
- 이후 특가 상품이 아닐 때도 promotion에서 활용하는 값들이 같이 넘어감(할인가 등)
- promotion 상태를 확인하여 특가 상태가 아니라면 관련 데이터 넘기지 않도록 설정
> fix: 상품 목록 보이지 않는 것 해결

- src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
- 주문 상세 내역 조회에서 이미지 매핑 정합성 오류 해결
- variant_id와 매핑되어야 하는데 코드 리팩토링으로 product_id와 매핑으로 변경
- product_id -> variant_id로 변경
> fix: 주문 내역 상세 조회 이미지 매핑 오류 해결

- src/main/java/com/kakaotech/ott/ott/global/config/SchedulingConfig.java
- src/main/java/com/kakaotech/ott/ott/global/config/ShedLockRedisConfig.java
- src/main/java/com/kakaotech/ott/ott/post/application/component/ViewCountAggregator.java
- src/main/java/com/kakaotech/ott/ott/recommendProduct/application/component/ClickCountAggregator.java
- 기존 게시글 및 추천 상품 조회에 대한 DB 최신화 작업은 단일 인스턴스 환경에서 적합하도록 설치
- 또한 로컬 메모리에 저장하여 DB에 최신화하기 때문에 서버가 다운되면 데이터 유실 위험 존재
- Redis Lock을 통해 멀티 인스턴스 환경에서 하나의 인스턴스만 DB에 값을 update 하도록 보장
- 로컬 메모리가 아닌 redis를 통해 서버가 다운되도 데이터 유실 보장
> feat: 게시글, 추천 상품 조회 배치 작업 Redis counter 적용

- .github/workflows/eks-deploy.yml
핵심 변경 내용
기존의 복잡한 SSH 배포 스크립트를 제거하고, ArgoCD를 활용한 GitOps 방식으로 EKS 개발 환경 배포 자동화
이제 feat/eks-deploy 브랜치에 코드를 푸시하면, GitHub Actions가 자동으로 새 Docker 이미지를 빌드하고 배포 설정 파일(deployment.yaml)의 이미지 태그를 업데이트합니다. 이후 ArgoCD가 이 변경을 감지하여 EKS 클러스터에 자동으로 배포를 반영
참고 사항
워크플로우 실행을 위해 DOCKERHUB_PAT, DOCKERHUB_USERNAME, MANIFEST_REPO_PAT Secret이 필요
ArgoCD는 100-hours-a-week/16-Hot6-cloud 레포지토리의 feat/k8s-manifests 브랜치를 추적하도록 설정되어야 함
> ArgoCD GitOps 기반의 EKS dev 환경 자동 배포 파이프라인 도입

- src/main/java/com/kakaotech/ott/ott/global/config/SchedulingConfig.java
- Main과 중복 선언으로 인해 config에서 제거
> fix: EnableScheduling 어노테이션 제거

- src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductVariantQueryRepositoryImpl.java
- variant와 promotion이 1:N 관계로 Left join을 실행했을 때 여러 개의 variant_id값을 가진 row가 중복으로 들어올 수 있음
- groupBy에서 역시 variant_id, promotion_id로 묶었기 때문에 variant_id가 같은 row 중복으로 조회
> fix: 제품 목록에서 특가 종료될 경우 중복 해결

- src/main/java/com/kakaotech/ott/ott/global/config/StreamConfig.java
- src/main/java/com/kakaotech/ott/ott/global/config/StreamConfigFactory.java
- src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
- src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostQueryRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/scrap/application/service/ScrapService.java
- src/main/java/com/kakaotech/ott/ott/scrap/application/serviceImpl/ScrapServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/scrap/domain/model/Scrap.java
- src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapJpaRepository.java
- src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapRepository.java
- src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/entity/ScrapEntity.java
- src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/repositoryImpl/ScrapRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/sycn/ScrapEvent.java
- src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/sycn/ScrapEventPublisher.java
- src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/sycn/ScrapSyncService.java
- src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/sycn/ScrapSyncServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/scrap/presentation/controller/ScrapController.java
- src/main/java/com/kakaotech/ott/ott/util/scheduler/ScrapPendingMessageRetryScheduler.java
- src/main/java/com/kakaotech/ott/ott/util/scheduler/ScrapRedisKey.java
- src/main/resources/db/migration/V9__scraps_new_column.sql
- 기존 스크랩 요청 및 취소 시 곧바로 DB 접근 방식 적용
- 요청 및 취소에 대한 API를 POST와 DELETE 메서드 방식으로 분리시켜 적용
- 수정 후 POST 하나의 API로 통합하여 toggle 방식 적용
- Redis Set에서 스크랩 상태를 파악하고 stream을 통해 DB로 비동기 처리
- 스크랩 종류에 따라 Stream 분리
> feat: Scrap 요청 및 취소 시 곧바로 DB 접근 방식 대신 Redis 방식 적용

- src/main/java/com/kakaotech/ott/ott/aiImage/application/service/AiImageService.java
- src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
- src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageJpaRepository.java
- src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageRepository.java
- src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
- src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
- src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
- 기존 이미지 생성 토큰 이미지 내역에서 조회
- 수정 후 이미지 테이블에서 성공 및 준비 데이터 모두 가져와 조회
- 이미지 준비중일 때 추가 생성 방지
> feat: 이미지 생성 토큰 유효성 검사 로직 변경
