100-hours-a-week/16-Hot6-be

src/main/java/com/kakaotech/ott/ott/aiImage/application/service/FastApiClient.java
src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/FastApiClientImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/request/FastApiRequestDto.java

AI FastApi RequestDto 변경

---

src/main/resources/application-dev.properties
src/main/resources/application-feat.properties
src/main/resources/application.properties

style: properties dev url로 변경

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java
src/main/resources/application-dev.properties
src/main/resources/application-feat.properties
src/main/resources/application.properties

style: redirect-url 변경

---

src/main/resources/application.properties

X-Forwarded-* 설정

---

src/main/resources/application.properties

properties에서 secrets.properties 파일 빌드 수정

bulid: secrets.propeties 파일 연결 설정

---

src/main/java/com/kakaotech/ott/ott/auth/presentation/OAuth2SuccessHandler.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java
src/main/resources/application.properties

Spring Security 설정을 통해 정적 자원보다 먼저 인증 경로 처리

security 설정 변경

---

src/main/java/com/kakaotech/ott/ott/auth/presentation/OAuth2SuccessHandler.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

accessToken 헤더 파라미터
refreshToken 쿠키 전달

accessToken, refreshToken 전달

---

src/main/java/com/kakaotech/ott/ott/auth/presentation/AuthController.java

refreshToken 재발급 url Api 명세서 경로로 변경

chore: refreshToken 재발급 url 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/FastApiClientImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java

feat:fastapi url 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/service/ImageUploader.java
src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/FastApiClientImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/S3Uploader.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java

S3 이미지 조회 url 변경
fastapi url 변경

feat: s3, fastapi url 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/service/AiImageService.java
src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/FastApiClientImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/S3Uploader.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/request/FastApiRequestDto.java
src/main/resources/application.properties

feat: 데스크 이미지 아닐 경우 s3 업로드된 이미지 삭제

---

src/main/java/com/kakaotech/ott/ott/like/application/service/LikeService.java
src/main/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImpl.java
src/main/java/com/kakaotech/ott/ott/like/domain/model/Like.java
src/main/java/com/kakaotech/ott/ott/like/domain/model/LikeType.java
src/main/java/com/kakaotech/ott/ott/like/domain/repository/LikeJpaRepository.java
src/main/java/com/kakaotech/ott/ott/like/domain/repository/LikeRepository.java
src/main/java/com/kakaotech/ott/ott/like/infrastructure/entity/LikeEntity.java
src/main/java/com/kakaotech/ott/ott/like/infrastructure/repositoryImpl/LikeRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/like/presentation/controller/LikeController.java
src/main/java/com/kakaotech/ott/ott/like/presentation/dto/request/LikeActiveRequestDto.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java

게시글에 대한 좋아요 활성 기능 완료 (게시글 좋아요 수 반영)

feat: 게시글 좋아요 활성 구현

---

src/main/java/com/kakaotech/ott/ott/like/application/service/LikeService.java
src/main/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImpl.java
src/main/java/com/kakaotech/ott/ott/like/domain/repository/LikeJpaRepository.java
src/main/java/com/kakaotech/ott/ott/like/infrastructure/repositoryImpl/LikeRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/like/presentation/controller/LikeController.java
src/main/java/com/kakaotech/ott/ott/like/presentation/dto/request/LikeRequestDto.java

게시글 좋아요 비활성화 구현 (게시글 좋아요 수 반영 완료)

feat: 게시글 좋아요 비활성화 구현

---

src/main/java/com/kakaotech/ott/ott/auth/presentation/OAuth2SuccessHandler.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/OAuthLoginResponseDto.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/UserResponseDto.java

feat: 로그인 ResponseDto 변경

---

src/main/java/com/kakaotech/ott/ott/auth/presentation/AuthController.java

feat: accessToken 재발급 responseDto message 변경

---

src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

Spring Security Oauth 로그인 트리거 uri 설정

feat: security oauth baseUri 설정

---

src/main/java/com/kakaotech/ott/ott/comment/application/service/CommentService.java
src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java
src/main/java/com/kakaotech/ott/ott/comment/domain/model/Comment.java
src/main/java/com/kakaotech/ott/ott/comment/domain/repository/CommentJpaRepository.java
src/main/java/com/kakaotech/ott/ott/comment/domain/repository/CommentRepository.java
src/main/java/com/kakaotech/ott/ott/comment/infrastructure/entity/CommentEntity.java
src/main/java/com/kakaotech/ott/ott/comment/infrastructure/repositoryImpl/CommentRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/comment/presentation/controller/CommentController.java
src/main/java/com/kakaotech/ott/ott/comment/presentation/dto/request/CommentRequestDto.java
src/main/java/com/kakaotech/ott/ott/comment/presentation/dto/response/CommentResponseDto.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java

comment 도메인 기능 완료
- 작성
- 수정
- 삭제

feat: comment 도메인 기능 완료

---

src/main/resources/application.properties

chore: SECRET 변수명 변경

---

src/main/java/com/kakaotech/ott/ott/global/config/WebConfig.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java

.onthe-top.com/ 하위 도메인에서 요청이 왔을 때 해당 브라우저들로 쿠키 전송

feat:최상위 도메인의 하위 도메인 쿠키 전송

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

chore: login url 변경

---

src/main/java/com/kakaotech/ott/ott/global/config/WebConfig.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

chore: cors 경로 변경

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

feat: HTTPS 기반으로 OAuth2 인증 URL 생성

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java

feat: accessToken 쿠키로 전달

---

.github/workflows/ci.yml

* main, dev 브랜치로 push시 gradle build가 이뤄집니다.
* 현재 dev에 직접 작업하고 계신 것으로 확인됩니다. dev 작업 끝나고 feat브랜치로부터 작업하실 때 합치시면 됩니다. 그 이전에 합치셔도 됩니다만, 매번 자동 빌드가 이뤄진다는 점만 기억해 주세요
* 작업 속도를 위해 스크립트를 미리 만들었으나, 지금은 빅뱅 배포 기간입니다. 당분간 빌드된 파일을 사용하지는 않습니다.

Backend CI 스크립트 작성

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/model/Post.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/entity/PostEntity.java
src/main/java/com/kakaotech/ott/ott/user/domain/model/User.java

feat: 회원가입, ai게시글 작성 시 포인트 적립 완료

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

feat: refreshToken 쿠키로 전송

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

feat: token 변경

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/RefreshTokenResponseDto.java

feat: 토큰 재발급 responseDto 수정

---

src/main/java/com/kakaotech/ott/ott/global/config/WebConfig.java

feat: config 변경

---

src/main/java/com/kakaotech/ott/ott/global/config/WebConfig.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

feat: springSecurity 수정

---

src/main/java/com/kakaotech/ott/ott/reply/application/service/ReplyService.java
src/main/java/com/kakaotech/ott/ott/reply/application/serviceImpl/ReplyServiceImpl.java
src/main/java/com/kakaotech/ott/ott/reply/presentation/controller/ReplyController.java
src/main/java/com/kakaotech/ott/ott/reply/presentation/dto/request/ReplyCreateRequestDto.java
src/main/java/com/kakaotech/ott/ott/reply/presentation/dto/response/ReplyCreateResponseDto.java

feat: reply 초기 세팅

---

src/main/java/com/kakaotech/ott/ott/HomeController.java
src/main/java/com/kakaotech/ott/ott/reply/application/service/ReplyService.java
src/main/java/com/kakaotech/ott/ott/reply/application/serviceImpl/ReplyServiceImpl.java
src/main/java/com/kakaotech/ott/ott/reply/domain/model/Reply.java
src/main/java/com/kakaotech/ott/ott/reply/domain/repository/ReplyJpaRepository.java
src/main/java/com/kakaotech/ott/ott/reply/domain/repository/ReplyRepository.java
src/main/java/com/kakaotech/ott/ott/reply/infrastructure/entity/ReplyEntity.java
src/main/java/com/kakaotech/ott/ott/reply/infrastructure/repositoryImpl/ReplyRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/reply/presentation/controller/ReplyController.java
src/main/java/com/kakaotech/ott/ott/reply/presentation/dto/response/ReplyCreateResponseDto.java
src/main/java/com/kakaotech/ott/ott/reply/presentation/dto/response/ReplyListResponseDto.java

feat: Reply 완료

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/ProductSubCategoryJpaRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/entity/ProductSubCategoryEntity.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/ProductMainCategoryRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/ProductSubCategoryRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java

feat: 카테고리 중복 저장 해결

---

src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/JwtService.java

feat: 예외처리 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

feat: ai 서버 jwt없이 접근 허용

---

src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

feat: ai 서버 jwt 요청 우회

---

src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java

feat: aiImageController 응답 코드 201 -> 200

---

src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/JwtService.java

feat: 토큰 로직 수정

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java

feat: AI 게시글 생성 시 해당 AI 이미지에 postId 값 적용

---

src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

feat: security url 추가

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/ProductDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/request/AiImageAndProductRequestDto.java

feat: 이미지 생성 실패 시 상태 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/response/AiImageAndProductResponseDto.java

feat: AI 이미지 응답 데이터 반환 수정

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageJpaRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/home/presentation/controller/HomeController.java
src/main/java/com/kakaotech/ott/ott/home/presentation/dto/response/MainResponseDto.java
src/main/java/com/kakaotech/ott/ott/post/application/service/PostService.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/response/PopularSetupDto.java
src/main/java/com/kakaotech/ott/ott/product/application/service/ProductDomainService.java
src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/DeskProductJpaRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/DeskProductRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductSubCategoryRepository.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/DeskProductRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductMainCategoryRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductSubCategoryRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/RecommendedItemsDto.java
src/main/java/com/kakaotech/ott/ott/scrap/application/serviceImpl/ScrapServiceImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapJpaRepository.java
src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapRepository.java
src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/repositoryImpl/ScrapRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/presentation/controller/ScrapController.java

feat: 메인 페이지 데이터 반환

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageJpaRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java
src/main/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/reply/application/serviceImpl/ReplyServiceImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/application/serviceImpl/ScrapServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/application/service/UserAuthService.java
src/main/java/com/kakaotech/ott/ott/user/application/service/UserService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/CustomUserDetailsService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthAuthServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/repository/UserAuthRepository.java
src/main/java/com/kakaotech/ott/ott/user/domain/service/UserDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/UserAuthAuthRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/MyDeskImageResponseDto.java

feat: 나의 데스크 조회

---

src/main/java/com/kakaotech/ott/ott/home/presentation/controller/HomeController.java

feat: main페이지 경로 변경

---

src/main/java/com/kakaotech/ott/ott/user/application/service/UserService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/repository/UserRepository.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/UserRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/MyInfoResponseDto.java

feat: 회원 정보 조회

---

src/main/java/com/kakaotech/ott/ott/user/application/service/UserService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/model/User.java
src/main/java/com/kakaotech/ott/ott/user/domain/repository/UserRepository.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/entity/UserEntity.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/UserRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/request/UserInfoUpdateRequestDto.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/UserInfoUpdateResponseDto.java

feat: 회원정보 수정 완료

---

src/main/java/com/kakaotech/ott/ott/user/application/service/UserService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/model/User.java
src/main/java/com/kakaotech/ott/ott/user/domain/repository/UserRepository.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/entity/UserEntity.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/UserRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/request/UserVerifiedRequestDto.java
src/main/resources/application.properties

feat: 추천인 코드 입력

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java

chore: 불필요한 import문 제거

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java

feat: jwt 예외 수정

---

src/main/java/com/kakaotech/ott/ott/post/application/component/AiImageLoader.java
src/main/java/com/kakaotech/ott/ott/post/application/component/FreeImageLoader.java
src/main/java/com/kakaotech/ott/ott/post/application/component/ImageLoader.java
src/main/java/com/kakaotech/ott/ott/post/application/component/ImageLoaderManager.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/request/FreePostCreateRequestDto.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/response/PostGetResponseDto.java
src/main/resources/application.properties

feat: 게시글 상세 조회 이미지 로드 분리

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/response/PostAllResponseDto.java

feat: 게시글 목록 조회 시 썸네일 리턴

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/response/AiImageResponseDto.java

feat: aiImage 조회 시 before, after이미지 반환

---

src/main/resources/application.properties

chore: 서버 타임존 설정
* 브랜치명 오타 났습니다.

chore: 서버 타임존 설정

---

src/main/java/com/kakaotech/ott/ott/post/application/service/PostService.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java

feat: 게시글 조회 방식 설정

---

src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java

fix: 카카오 토큰 존재해도 jwt 판단 후 로그인 처리

fix: 카카오 토큰 존재해도 jwt 판단 후 로그인 처리

---

src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java

fix: 페이지 조회 쿼리 파라미터 순서 변경

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/JwtService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/repository/RefreshTokenJpaRepository.java
src/main/java/com/kakaotech/ott/ott/user/domain/repository/RefreshTokenRepository.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/RefreshTokenRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/UserAuthRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java

fix: login 수정

---

src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

fix: security 허용 url 수정

---

src/main/resources/application-prod.properties

fix: prod properties 생성

---

src/main/java/com/kakaotech/ott/ott/post/presentation/dto/request/FreePostCreateRequestDto.java

fix: 자유 게시판 작성 수정

---

src/main/java/com/kakaotech/ott/ott/post/application/service/PostService.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java

fix: 게시글 조회 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageJpaRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/application/service/UserService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

fix: 나의 데스크 조회 수정

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/response/PostGetResponseDto.java

fix: aiImage Success만 반환

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java

fix: 게시글 조회 수정

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

fix: 접근 URL 수정

---

src/main/java/com/kakaotech/ott/ott/home/presentation/controller/HomeController.java
src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductDomainServiceImpl.java

fix: 메인 페이지 데이터 조회 버그 수정

---

src/main/resources/application-feat.properties
src/main/resources/application.properties

fix: properties 변경

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

fix: jwt 필터 수정

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/request/FreePostCreateRequestDto.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/request/FreePostUpdateRequestDto.java
src/main/java/com/kakaotech/ott/ott/postImage/domain/PostImage.java
src/main/java/com/kakaotech/ott/ott/postImage/entity/PostImageEntity.java
src/main/java/com/kakaotech/ott/ott/util/validator/ImageCountValidator.java
src/main/java/com/kakaotech/ott/ott/util/validator/ValidImageCount.java

fix: 자유 게시판 수정 이미지 처리 완료

---

src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/RecommendedItemsDto.java

fix: 메인페이지 product 구매 링크 포함

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java

fix: 게시글 조회 시 사용자 구분

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java

fix: post 조회 개선

---

src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java

fix: refresh 토큰 만료 시 클라이언트 쿠키 만료

fix: refresh 토큰 만료 시 클라이언트 쿠키 만료

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/ott/ott/user/application/service/UserAuthService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/JwtService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/RefreshTokenRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java

fix: 로그인 토큰 로직 수정

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageJpaRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/application/service/UserService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

fix: 나의 데스크 조회 필터링

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java
src/main/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/reply/application/serviceImpl/ReplyServiceImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/application/serviceImpl/ScrapServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/CustomUserDetailsService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/repository/UserAuthRepository.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/UserAuthRepositoryImpl.java

chore: userRepository 리팩토링

---

.github/workflows/deploy.yml

* 이제 로그가 /var/log/onthetop/backend/backend.log에 출력됩니다.

로그 출력 위치 변경

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/JwtService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java

fix: refreshToken 내용 수정

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java

fix: 로그인 에러 수정

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/CustomOAuth2UserService.java

fix: 로그인 수정

---

src/main/java/com/kakaotech/ott/ott/global/security/JwtAuthenticationFilter.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/JwtService.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java

fix: jwt 수정

---

src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java

fix: Transactinal 설정

---

src/main/java/com/kakaotech/ott/ott/like/presentation/dto/request/LikeRequestDto.java
src/main/java/com/kakaotech/ott/ott/scrap/presentation/dto/request/ScrapRequestDto.java

fix: like, scrap dto 수정

---

src/main/java/com/kakaotech/ott/ott/post/application/component/PostWeightUpdater.java

fix: 게시글 weight 반영 시간 변경'

---

src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/reply/application/serviceImpl/ReplyServiceImpl.java

feat: 사용자 탈퇴 시 게시글, 댓글, 답글 알 수 없음으로 처리

feat: 사용자 탈퇴 시 게시글, 댓글, 답글 알 수 없음으로 처리

---

src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java
src/main/java/com/kakaotech/ott/ott/comment/infrastructure/repositoryImpl/CommentRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java

fix: comment 삭제 에러 해결

---

src/main/java/com/kakaotech/ott/ott/comment/domain/repository/CommentJpaRepository.java
src/main/java/com/kakaotech/ott/ott/comment/domain/repository/CommentRepository.java
src/main/java/com/kakaotech/ott/ott/comment/infrastructure/repositoryImpl/CommentRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/like/domain/repository/LikeJpaRepository.java
src/main/java/com/kakaotech/ott/ott/like/domain/repository/LikeRepository.java
src/main/java/com/kakaotech/ott/ott/like/infrastructure/repositoryImpl/LikeRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapJpaRepository.java
src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapRepository.java
src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/repositoryImpl/ScrapRepositoryImpl.java

fix: 게시글에 대한 좋아요, 댓글, 스크랩 수 정합성 해결

fix: 게시글에 대한 좋아요, 댓글, 스크랩 수 정합성 해결

---

src/main/java/com/kakaotech/ott/ott/comment/domain/repository/CommentJpaRepository.java
src/main/java/com/kakaotech/ott/ott/like/domain/repository/LikeJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapJpaRepository.java
src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapRepository.java
src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/repositoryImpl/ScrapRepositoryImpl.java

fix: 게시글 댓글, 스크랩, 좋아요 수 조회 에러 해결

fix: 게시글 댓글, 스크랩, 좋아요 수 조회 에러 해결

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java

fix: 게시글 조회 에러 해결

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/model/User.java

fix: 포인트 정책 변경

---

.github/workflows/deploy.yml

nohup내부로 환경 변수 삽입

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java

fix: AI 게시글 수정 에러 해결

---

src/main/java/com/kakaotech/ott/ott/post/presentation/dto/request/AiPostCreateRequestDto.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/request/AiPostUpdateRequestDto.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/request/FreePostCreateRequestDto.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/request/FreePostUpdateRequestDto.java

fix: dto 길이 제한

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java

fix: AI 이미지 조회 시 상품 스크랩 에러 해결

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java
src/main/resources/application-dev.properties
src/main/resources/application-prod.properties
src/main/resources/application.properties

fix: OAuth redirectURL 개발 환경 동적 로딩

fix: OAuth redirectURL 개발 환경 동적 로딩

---

src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/DeskProductJpaRepository.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/DeskProductRepositoryImpl.java

fix: jpa 에러 제거

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java

fix: 쿼리 파라미터명 변경

---

src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserController.java
src/main/resources/application.properties

feat: 사용자 탈퇴 시 기본 프로필 설정

---

src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java
src/main/java/com/kakaotech/ott/ott/post/domain/model/MyDeskState.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java

fix: 접근 도메인 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageJpaRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/model/MyDeskState.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/MyDeskImageResponseDto.java

fix: 나의 데스크 조회 개선

---

src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

fix: securityconfig 수정

---

src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/MyPostResponseDto.java

fix: config 수정

---

src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java

fix: 로그아웃 시 refreshToken DB에서 삭제

fix: 로그아웃 시 refreshToken DB에서 삭제

---

src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/JwtService.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/entity/RefreshTokenEntity.java

fix: 로그아웃 후 재로그인 또는 토큰 재발급 시 DB와 검증

fix: 로그아웃 후 재로그인 또는 토큰 재발급 시 DB와 검증

---

src/main/resources/application-prod.properties

REDIRECT URL 수정

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/FastApiClientImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/controller/UserAuthController.java
src/main/resources/application-dev.properties
src/main/resources/application-prod.properties
src/main/resources/application.properties

dev, prod 환경 baseUrl 매칭

---

src/main/java/com/kakaotech/ott/ott/comment/presentation/controller/CommentController.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

fix: 비로그인 사용자 댓글 조회 가능

---

src/main/java/com/kakaotech/ott/ott/post/application/service/PostService.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/response/PostAllResponseDto.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java

fix: 게시글 조건 조회 시 lastLike, lastView의 Count값 전달

fix: 게시글 조건 조회 시 lastLike, lastView의 Count값 전달

---

.github/workflows/release.yml

* 버저닝을 위해 github actions 상에서 push가 필요한데 권한 부여를 위해 PAT을 생성해 봤습니다.

cd: PAT 사용하도록 추가

---

src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/user/application/service/UserAuthService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java

- merge할 브랜치의 위치를 확인해 주세요 (master/main ❌)
- 리뷰가 필요한 경우 'review' 라벨을 달아주고, 리뷰어를 지정해 주세요
- Approve된 PR은 리뷰어가 머지를 하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.
<br>
> 설명: PR의 핵심 변경 사항을 간결하게 요약합니다.
이미지 업로드 페이지에서 사용자의 남은 이미지 생성 토큰 확인 가능하도록 수정
- 사용자가 자신의 이미지 생성 가능 토큰을 파악하도록 하기 위해
> 설명: 기능이 잘 동작하는지 로컬에서 확인할 수 있는 절차를 기술합니다.
1. Postman에서 `GET /api/v1/ai-images/upload로 반환되는지 확인

fix: 이미지 생성 토큰 확인 로직 변경

---

src/main/resources/application-dev.properties

- 테스트를 위해 dev backend 서버에 prod AI 서버 연결

fix: AI 서버 임시 연결 조치

---

src/main/resources/application-dev.properties

fix: properties 정상화

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java

- Read 메서드 읽기 전용 모드로 설정
- 쓰기 작업 있을 경우 예외 감지
- 불필요한 쓰기 작업 생략하여 성능 개선

fix: postService @Transactional(readOnly = true) 설정

---

src/test/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImplTest.java
src/test/java/com/kakaotech/ott/ott/like/domain/model/LikeTest.java

- Like 도메인 객체와 LikeService에 대한 단위 테스트 코드를 작성했습니다.
- 해당 테스트 코드의 클래스, 메서드, 줄, 브랜치 커버리지 100% 달성
- LikeTest, LikeServiceImplTest 클래스에서 cntl + R 또는 커버리지로 실행 클릭

feat: Like, LikeService 테스트 코드 작성

---

src/test/java/com/kakaotech/ott/ott/like/presentation/controller/LikeControllerTest.java

- LikeController에 대한 Unit Test Code 작성
- MockMvc 없이 직접 호출하기 때문에 실제 Spring boot 컨텍스트를 타지 않음
- 그렇기 때문에 커버리지 도구가 @Controller의 실제 요청-응답을 인식하지 못함

feat: LikeController Unit Test Code 작성

---

src/test/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImplTest.java
src/test/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceIntegrationTest.java
src/test/java/com/kakaotech/ott/ott/like/domain/model/LikeTest.java
src/test/java/com/kakaotech/ott/ott/like/infrastructure/repositoryImpl/LikeRepositoryImplTest.java
src/test/java/com/kakaotech/ott/ott/like/presentation/controller/LikeControllerTest.java

- Like의 Test 메서드명 컨벤션 적용
- 영어 -> 한글 메서드명으로 변경

chore: like Test 메서드명 변경

---

src/main/resources/application-feat.properties

feat: feat.properties 설정 변경

---

src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItem.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItemStatus.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/RefundReason.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemJpaRepository.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemRepository.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/entity/OrderItemEntity.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/repositoryImpl/OrderItemRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/service/ProductOrderService.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrder.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrderStaus.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderJpaRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/entity/ProductOrderEntity.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/controller/ProductOrderController.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/request/ProductOrderRequestDto.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/request/ServiceProductDto.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/response/ProductOrderResponseDto.java

- 주문 생성(요청) 기능 구현
- productId, pending_product_pid 존재 시 주문 불가 예외 처리 구현(중복 주문 방지)
- 주문과 주문 상품에 대한 1:N 관계 구현
- 할인 총액 추후 반영

371 feat/order create

---

src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderJpaRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java

fix: 조회 시 삭제된 주문 내역 제외

---

src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/request/ProductOrderPartialCancelRequestDto.java
src/main/java/com/kakaotech/ott/ott/user/application/service/UserAuthService.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java

fix: AI 이미지 생성 토큰 확인 해결

---

src/main/java/com/kakaotech/ott/ott/productOrder/application/service/ProductOrderService.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrder.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrderStatus.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderJpaRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/entity/ProductOrderEntity.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/controller/ProductOrderController.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/request/ProductOrderPartialConfirmRequestDto.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/response/MyProductOrderHistoryResponseDto.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/response/MyProductOrderResponseDto.java

- FE와 연동 후 에러 해결
- dto 데이터 추가 및 수정
- Transactional 설정 및 수정
- 비즈니스 로직 변경 및 추가

fix: ProductOrder 도메인 기능 보완

---

src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItem.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItemStatus.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemRepository.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/entity/OrderItemEntity.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/repositoryImpl/OrderItemRepositoryImpl.java

- orderItem 관리 상태 수정
- repository 저장 로직 변경
- productOrder 호출 메서드 추가
- 도메인 로직 추가 및 수정

fix: orderItem 도메인 에러 해결

---

src/main/resources/application.properties

fix: dev properties변경

---

src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/pointHistory/domain/model/PointActionReason.java
src/main/java/com/kakaotech/ott/ott/pointHistory/domain/model/PointHistory.java
src/main/java/com/kakaotech/ott/ott/pointHistory/domain/repository/PointHistoryJpaRepository.java
src/main/java/com/kakaotech/ott/ott/pointHistory/domain/repository/PointHistoryRepository.java
src/main/java/com/kakaotech/ott/ott/pointHistory/infrastructure/entity/PointHistoryEntity.java
src/main/java/com/kakaotech/ott/ott/pointHistory/infrastructure/repositoryImpl/PointHistoryRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/service/UserDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/MyPointHistoryResponseDto.java

- 포인트 내역 조회 보완
- 회원가입 및 게시글 작성 시 포인트 지급 적용
- 포인트 적립 사유 및 상태 관리
- User의 Point 이동 필요

feat: 포인트 내역 조회 보완 및 정책 적용

---

src/main/java/com/kakaotech/ott/ott/product/application/service/ProductService.java
src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/domain/model/ProductVariant.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductJpaRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductRepository.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/presentation/controller/ProductController.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/ProductGetResponseDto.java
src/main/java/com/kakaotech/ott/ott/scrap/application/serviceImpl/ScrapServiceImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/domain/model/ScrapType.java

이번 PR은 상품 상세 조회기능을 추가하기 위해
- ProductController에 GET 요청 엔드포인트 추가
- 상세조회 비즈니스 로직 구현
- 판매되는 상품(ACTIVE)만 조회할 수 있도록 로직 작성
- 스크랩 여부를 판단하기 위해 스크랩 코드 변경
- 스크랩 증감 코드 통합

388 feat/get product detail

---

src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductRepository.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java

- 나의 스크랩 조회 시 게시글, 추천 상품 조회에서 게시글, 추천 상품, 서비스 판매 상품으로 변경
- ScrapType으로 구분하여 썸네일 이미지 설정

feat: 나의 스크랩 조회 시 서비스 상품 추가

---

src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductServiceImpl.java

- Product 조회 오류 해결
- Service에서 findById Optional 형태로 받는 로직 Product로 받도록 수정

fix: Product 조회 오류 해결

---

src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java

- 게시글 목록 페이지 조회 에러 해결
- DB 정합성 문제 발생

fix: 게시글 목록 페이지 에러 해결

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/AiImageJpaRepository.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/MyDeskImageResponseDto.java
src/main/java/com/kakaotech/ott/ott/user/presentation/dto/response/MyPostResponseDto.java

- 나의 데스크 조회 기능 보완
- Pagination 데이터 분리
- jpa jpql 쿼리문 수정

feat: 나의 데스크 조회 기능 보완

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/response/AiImageResponseDto.java

- 데스크 이미지 생성 후 추천 제품에 대해서 이미지에 좌표값 추출
- 객체의 상대 위치값으로 RecommendProduct의 x, y좌표값 저장

feat: 제품 좌표값 설정

---

src/main/java/com/kakaotech/ott/ott/product/domain/model/ProductPromotion.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductPromotionJpaRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductPromotionRepository.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductPromotionRepositoryImpl.java

- 특가 상품 도메인의 비즈니스 로직 추가(수량 증감)
- Repository에서 반환값 Optional -> 도메인 타입으로 변경

feat: 특가 상품에 대한 비즈니스 로직 추가

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/model/ImageGenerationHistory.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/ImageGenerationHistoryJpaRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/domain/repository/ImageGenerationHistoryRepository.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/entity/ImageGenerationHistoryEntity.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/ImageGenerationHistoryRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/domain/model/ProductPromotion.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductImageJpaRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductImageRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductPromotionRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductVariantRepository.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/entity/ProductImageEntity.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductPromotionRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductVariantRepositoryImpl.java

feat: product 관련 repository 반환 타입 변경

---

src/main/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImpl.java
src/main/java/com/kakaotech/ott/ott/like/domain/model/Like.java
src/main/java/com/kakaotech/ott/ott/like/domain/model/LikeType.java
src/main/java/com/kakaotech/ott/ott/like/domain/repository/LikeJpaRepository.java
src/main/java/com/kakaotech/ott/ott/like/domain/repository/LikeRepository.java
src/main/java/com/kakaotech/ott/ott/like/infrastructure/entity/LikeEntity.java
src/main/java/com/kakaotech/ott/ott/like/infrastructure/repositoryImpl/LikeRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/like/presentation/dto/request/LikeRequestDto.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/model/Post.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/entity/PostEntity.java
src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/response/PostAllResponseDto.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/response/PostGetResponseDto.java

- 좋아요를 게시글에 종속된 형태로 변경
- 상품에 좋아요 기능 제거, 게시글에만 해당하여 front에서 전송하는 형태 변경
- 테이블 형태 변경

feat: like 게시글에 종속된 형태로 변경

---

src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java

- ImageGenerationHistory 반영된 코드 추가

feat: AI 이미지 생성 내역 반영 파일 추가

---

src/main/java/com/kakaotech/ott/ott/recommendProduct/application/serviceImpl/DeskProductServiceImpl.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/presentation/controller/DeskProductController.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/presentation/dto/response/DeskProductListResponseDto.java

- 데스크 상세 조회 컨트롤러 추가
- 목록 페이지 dto subCategory 추가

feat: 데스크 추천 상품 상세 조회 컨트롤러 추가 및 dto 변경

---

src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/product/application/service/ProductService.java
src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/domain/model/ProductPromotion.java
src/main/java/com/kakaotech/ott/ott/product/domain/model/ProductVariant.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductJpaRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductPromotionJpaRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductPromotionRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductVariantJpaRepository.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductVariantRepository.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/entity/ProductPromotionEntity.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/entity/ProductVariantEntity.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductPromotionRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductVariantRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/presentation/controller/ProductController.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/request/PromotionDto.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/request/VariantDto.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/ProductGetResponseDto.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/ProductListResponseDto.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java

이번 PR은 상품 목록 조회 기능을 추가하기 위해서 Cursor 기반 페이지네이션을 적용했습니다.
- 일반상품
- 품목별 목록 조회 구현
- 전체 목록 조회 구현
- 특가상품
- 특가 종류(일일/깜짝 특가)에 따른 목록 조회 구현
또한, `variant`와 `promotion` 재고 관리 필드 변경을 반영했습니다.
기존에는 `reserved_quantity`와 `sold_quantity`로 관리하였으나, 총 재고 `total_quantity` 필드를 추가해서 관리하고 있습니다.

387-product-list

---

src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java

상품 목록/상세 페이지는 게시글과 마찬가지로 비로그인 사용자가 접근할 수 있도록 합니다.

fix: 상품 목록, 상세 페이지 비로그인 사용자 접근 허용

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/entity/AiImageEntity.java
src/main/java/com/kakaotech/ott/ott/aiImage/infrastructure/repositoryImpl/AiImageRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/request/AiImageAndProductRequestDto.java
src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/request/AiImageUploadRequestDto.java
src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserAuthServiceImpl.java

- fast api dto 변경
- 이미지 생성 토큰 검증 변경

feat: fast api 요청 데이터 변경 및 ai image 요청 로직 변경

---

src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItem.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemRepository.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/entity/OrderItemEntity.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/repositoryImpl/OrderItemRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/payment/application/service/PaymentService.java
src/main/java/com/kakaotech/ott/ott/payment/application/serviceImpl/PaymentServiceImpl.java
src/main/java/com/kakaotech/ott/ott/payment/domain/model/Payment.java
src/main/java/com/kakaotech/ott/ott/payment/domain/model/PaymentMethod.java
src/main/java/com/kakaotech/ott/ott/payment/domain/model/PaymentStatus.java
src/main/java/com/kakaotech/ott/ott/payment/domain/repository/PaymentJpaRepository.java
src/main/java/com/kakaotech/ott/ott/payment/domain/repository/PaymentRepository.java
src/main/java/com/kakaotech/ott/ott/payment/infrastructure/entity/PaymentEntity.java
src/main/java/com/kakaotech/ott/ott/payment/infrastructure/repositoryImpl/PaymentRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/payment/presentation/controller/PaymentController.java
src/main/java/com/kakaotech/ott/ott/payment/presentation/dto/request/PaymentRequestDto.java
src/main/java/com/kakaotech/ott/ott/payment/presentation/dto/response/PaymentResponseDto.java
src/main/java/com/kakaotech/ott/ott/pointHistory/domain/model/PointHistory.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/request/ServiceProductDto.java

- 결제 요청 기능 추가
- 제출 포인트 부족 시 예외 처리 완료
- 보유 포인트 부족 시 예외 처리 완료
- 이미 결제한 주문 예외 처리 완료
- 포인트 내역 테이블 반영 완료
- 주문 상품 및 주문 테이블 반영 완료

feat: 결제 요청 기능 및 포인트 내역, 주문, 주문 상품 반영 완료

---

src/main/java/com/kakaotech/ott/ott/productOrder/application/component/OrderDeleteBatchJob.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderJpaRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java

- 상품 주문 후 30동안 결제 요청 없을 시 주문 내역 삭제 처리 (매분 배치 함수 실행)
- 주문 확정 자동 처리 기간 설정 (3일)

feat: 주문 대기 상태 자동 삭제 처리(배치) 및 주문 확정 배치 코드 수정

---

src/main/java/com/kakaotech/ott/ott/admin/application/AdminService.java
src/main/java/com/kakaotech/ott/ott/admin/application/AdminServiceImpl.java
src/main/java/com/kakaotech/ott/ott/admin/presentation/controller/AdminController.java
src/main/java/com/kakaotech/ott/ott/admin/presentation/dto/response/AdminProductStatusResponseDto.java
src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/global/security/SecurityConfig.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItemStatus.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemJpaRepository.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemRepository.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/repositoryImpl/OrderItemRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductServiceImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/model/Role.java
src/main/java/com/kakaotech/ott/ott/user/domain/model/UserPrincipal.java

- 관리자 전용 상품 환불 요청 및 결제 완료 상품 조회 api
- role이 ROLE_ADMIN인 user만 허용

feat: 관리자 전용 사용자 환불 및 결제 완료 제품 리스트 조회

---

src/main/java/com/kakaotech/ott/ott/admin/application/AdminService.java
src/main/java/com/kakaotech/ott/ott/admin/application/AdminServiceImpl.java
src/main/java/com/kakaotech/ott/ott/admin/presentation/controller/AdminController.java
src/main/java/com/kakaotech/ott/ott/admin/presentation/dto/response/AdminDeliveryResponseDto.java
src/main/java/com/kakaotech/ott/ott/admin/presentation/dto/response/AdminRefundResponseDto.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItem.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemJpaRepository.java
src/main/java/com/kakaotech/ott/ott/orderItem/domain/repository/OrderItemRepository.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/entity/OrderItemEntity.java
src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/repositoryImpl/OrderItemRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/model/ProductOrder.java
src/main/java/com/kakaotech/ott/ott/productOrder/domain/repository/ProductOrderRepository.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java

- 관리자 배달 완료 api 추가
- 관리자 환불 요청 승인 api 추가
- 부분 환불, 전체 환불 처리 완료

feat: 관리자 배달 완료 및 환불 요청 승인 기능 추가

---

src/main/java/com/kakaotech/ott/ott/admin/application/AdminServiceImpl.java
src/main/java/com/kakaotech/ott/ott/admin/presentation/dto/response/AdminProductStatusResponseDto.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/infrastructure/repositoryImpl/ProductOrderRepositoryImpl.java

- 응답 dto 구조 변경
- 배송 완료 주문 단위로 변경(기존 : 상품 단위)

feat: 관리자 페이지 dto 변경 및 배달 완료 로직 변경

---

src/main/java/com/kakaotech/ott/ott/admin/application/AdminServiceImpl.java
src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/payment/domain/model/Payment.java
src/main/java/com/kakaotech/ott/ott/payment/domain/model/PaymentStatus.java
src/main/java/com/kakaotech/ott/ott/payment/domain/repository/PaymentJpaRepository.java
src/main/java/com/kakaotech/ott/ott/payment/domain/repository/PaymentRepository.java
src/main/java/com/kakaotech/ott/ott/payment/infrastructure/entity/PaymentEntity.java
src/main/java/com/kakaotech/ott/ott/payment/infrastructure/repositoryImpl/PaymentRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java

feat: 환불 및 취소 시 payment 상태 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/presentation/controller/AiImageController.java

feat: AI 이미지 컨셉 추가

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/model/AiImageConcept.java

fix: AI 컨셉트 추가

---

src/main/java/com/kakaotech/ott/ott/orderItem/infrastructure/entity/OrderItemEntity.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java

- refundAmount가 entity에서 잘못 저장되고 있는 문제 해결

fix: refundAmount 값 오류 해결

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/AiImageServiceImpl.java
src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java

fix: 이미지 생성 실패 분기 처리

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/model/AiImageConcept.java

fix: CARTOON 컨셉 임시 제거

---

src/main/java/com/kakaotech/ott/ott/product/application/component/PromotionEndBatch.java
src/main/java/com/kakaotech/ott/ott/product/domain/repository/ProductPromotionJpaRepository.java

fix: 특가 종료 배치 처리 SOLD_OUT 포함

---

build.gradle
src/main/java/com/kakaotech/ott/ott/pointHistory/domain/model/PointActionReason.java
src/main/java/com/kakaotech/ott/ott/post/application/service/PostService.java
src/main/java/com/kakaotech/ott/ott/post/application/serviceImpl/PostServiceImpl.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostJpaRepository.java
src/main/java/com/kakaotech/ott/ott/post/domain/repository/PostRepository.java
src/main/java/com/kakaotech/ott/ott/post/infrastructure/repositoryImpl/PostRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/post/presentation/controller/PostController.java
src/main/java/com/kakaotech/ott/ott/post/presentation/dto/response/PostAllResponseDto.java
src/main/resources/db/migration/V1__baseline.sql
src/main/resources/db/migration/V2__truncate_old_data.sql
src/main/resources/db/migration/V3__alter_existing_tables.sql
src/main/resources/db/migration/V4__create_new_tables.sql
src/main/resources/db/migration/V5__migrate_point_data.sql
src/main/resources/db/migration/V6__drop_old_column.sql

- 인기 데스크 셋업 조회 추가
- flyway DB 버전 관리 추가

feat: 인기 데스크 셋업 게시글 조회 추가

---

src/main/java/com/kakaotech/ott/ott/user/application/serviceImpl/UserServiceImpl.java

feat: 나의 게시글 조회 dto 변경

---

src/main/resources/application.properties

fix: DB 서버 변경

---

src/main/java/com/kakaotech/ott/ott/product/domain/model/ProductType.java

fix: product 카테고리 변경

---

src/main/resources/application-dev.properties
src/main/resources/application-prod.properties

feat: properties flyway 적용

---

src/main/java/com/kakaotech/ott/ott/pointHistory/domain/model/PointHistory.java

fix: 주석 제거

---

src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/DeskProductJpaRepository.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/presentation/controller/DeskProductController.java

fix: 추천 제품 리스트 무한 스크롤 오류 제거

---

src/main/java/com/kakaotech/ott/ott/aiImage/presentation/dto/request/AiImageAndProductRequestDto.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/presentation/dto/request/ProductDetailRequestDto.java

fix: 이미지 생성 dto 오류 해결

---

src/test/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceImplTest.java
src/test/java/com/kakaotech/ott/ott/like/application/serviceImpl/LikeServiceIntegrationTest.java
src/test/java/com/kakaotech/ott/ott/like/domain/model/LikeTest.java
src/test/java/com/kakaotech/ott/ott/like/infrastructure/repositoryImpl/LikeRepositoryImplTest.java
src/test/java/com/kakaotech/ott/ott/like/presentation/controller/LikeControllerTest.java
src/test/java/com/kakaotech/ott/ott/like/presentation/controller/LikeWebMvcControllerTest.java

- Like 테스트 코드 로직 변경
- 기존 Like.Type이 제거되어, 해당 부분 삭제
- targetId -> postId로 변경

fix: Like 테스트 코드 변경

---

src/main/java/com/kakaotech/ott/ott/aiImage/domain/model/AiImageConcept.java

fix: 이미지 생성 컨셉 cartoon rollback

---

src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/FastApiClientImpl.java
src/main/java/com/kakaotech/ott/ott/aiImage/application/serviceImpl/S3Uploader.java
src/main/java/com/kakaotech/ott/ott/product/application/component/PromotionEndBatch.java

feat: 트랜잭션 설정

---

src/main/java/com/kakaotech/ott/ott/user/presentation/controller/OAuth2SuccessHandler.java
src/main/resources/application-dev.properties
src/main/resources/application-feat.properties
src/main/resources/application-prod.properties

feat: 실행 서버 환경에 따라 cookie 설정 동적 변경

---

src/main/resources/application-dev.properties

fix: properties domain 변경

---

src/main/java/com/kakaotech/ott/ott/comment/application/serviceImpl/CommentServiceImpl.java
src/main/java/com/kakaotech/ott/ott/user/domain/repository/UserAuthRepository.java
src/main/java/com/kakaotech/ott/ott/user/infrastructure/repositoryImpl/UserAuthRepositoryImpl.java

- 댓글 목록 조회 N+1 문제 해결
- 댓글 1페이지 조회 시 사용자 10번 조회
- 댓글 1페이지 조회 시 사용자 1번 조회로 변경

feat: 댓글 N+1 문제 해결

---

src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/product/domain/model/ProductPromotion.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java

- 기존 특가 상품의 판매 시간 전에 구매 요청 시(Postman 등) 요청 성공
- 수정 후 404 반환

feat: 특가 상품 판매 시작 전 구매 요청 시 404 반환

---

src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/ProductGetResponseDto.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/ProductListResponseDto.java

> 설명: PR의 핵심 변경 사항을 간결하게 요약합니다.
- DB에 기록된 시간이 UTC로 인삭하여, KST 시간으로 변환 후 응답하는 오류 해결

fix:시작/종료 시각 KST 적용 이슈 해결

---

src/main/java/com/kakaotech/ott/ott/product/application/serviceImpl/ProductServiceImpl.java
src/main/java/com/kakaotech/ott/ott/product/presentation/dto/response/ProductGetResponseDto.java

fix: getDto 시작/종료 시각 rollback

---

src/main/java/com/kakaotech/ott/ott/product/infrastructure/repositoryImpl/ProductVariantQueryRepositoryImpl.java

fix: 상품 목록 조회

---

src/main/resources/application-prod.properties

fix: properties 수정

---

src/main/java/com/kakaotech/ott/ott/orderItem/domain/model/OrderItem.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java
src/main/java/com/kakaotech/ott/ott/productOrder/presentation/dto/response/ProductOrderResponseDto.java
src/main/java/com/kakaotech/ott/ott/util/KstDateTime.java

- OrderItem 내부에서 데이터 가공 후 저장
- 각 메서드의 중복 코드 private 내부 함수로 묶어서 코드 중복 제거
- 하나의 메서드에서 발생하는 책임을 private 메서드로 분리하여 책임 분리
- KstDateTime null 처리

feat: ProductOrderServiceImpl 리팩토링

---

src/main/java/com/kakaotech/ott/ott/productOrder/application/serviceimpl/ProductOrderServiceImpl.java

- 주문 내역 상세 조회 메서드 책임 분리
- private 메서드로 클래스 내부 메서드로 분리

feat: 주문 내역 상세 조회 리팩토링

---

src/main/java/com/kakaotech/ott/ott/recommendProduct/application/serviceImpl/ProductDomainServiceImpl.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/DeskProductJpaRepository.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/DeskProductRepository.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/ProductMainCategoryJpaRepository.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/ProductMainCategoryRepository.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/ProductSubCategoryJpaRepository.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/domain/repository/ProductSubCategoryRepository.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/infrastructure/repositoryImpl/DeskProductRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/infrastructure/repositoryImpl/ProductSubCategoryRepositoryImpl.java

- 쿼리 반복문마다 DB 요청 -> Map으로 한번에 조회 후 진행하는 로직으로 변경
- 메소드 분리
- AI 서버와 테스트 목적

feat: 추천 제품 저장 로직 리팩토링 테스트

---

src/main/java/com/kakaotech/ott/ott/global/exception/ErrorCode.java
src/main/java/com/kakaotech/ott/ott/recommendProduct/infrastructure/repositoryImpl/ProductMainCategoryRepositoryImpl.java

fix: ErrorCode 파일 올리지 않아 빌드 실패도 재배포

---

build.gradle
src/main/java/com/kakaotech/ott/ott/global/config/RedisCacheConfig.java
src/main/java/com/kakaotech/ott/ott/global/config/RedisConfig.java
src/main/java/com/kakaotech/ott/ott/util/scheduler/CacheEvictionScheduler.java
src/main/resources/application-dev.properties
src/main/resources/application-feat.properties
src/main/resources/application-prod.properties
src/main/resources/application.properties

- 캐시별 TTL 정책 관리
- RedisTemplate 설정: <key, value> 템플릿 설정
- 메인 페이지 캐싱 무효화 적용을 위한 스케줄러 등록
- 인기 게시글, 인기 제품: 매일 자정 갱신
- 오늘의 특가: 매일 오후 1시 갱신

529-mainpage-cache

---

build.gradle

- build.gradle 같이 push 하지 않아 에러 발생

feat: 의존성 미주입으로 에러 해결

---

src/main/resources/application-dev.properties
src/main/resources/application-feat.properties
src/main/resources/application-prod.properties

- feat, dev, prod 환경의 sentinel 주소 변경

fix: sentinel 노드 주소 변경

---

src/main/java/com/kakaotech/ott/ott/batch/application/component/BatchExecutor.java
src/main/java/com/kakaotech/ott/ott/productOrder/application/component/OrderDeleteBatchJob.java

- 30분 동안 미결제 주문에 대한 예약재고 Rollback

Fix: reservation cancel

---

src/main/java/com/kakaotech/ott/ott/admin/application/AdminServiceImpl.java

- `productVariant.getCreatedAt()` → `payment.getPaidAt()`

fix: 결제일 필드 dto 매핑 오류 해결

---

src/main/java/com/kakaotech/ott/ott/productOrder/application/component/OrderDeleteBatchJob.java

- 30 → 5분 동안 결제 미 진행 시 주문 자동 취소

fix: 30 -> 5분 동안 결제 미 진행 시 주문 자동 취소

---

src/main/java/com/kakaotech/ott/ott/post/application/component/ViewCountAggregator.java

- RedisTemplate<String, Object> -> RedisTemplate<String, String> 으로 변경

fix: RedisTemplate 타입 변경

---

src/main/java/com/kakaotech/ott/ott/like/infrastructure/repositoryImpl/LikeRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/like/infrastructure/sync/LikeSyncServiceImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/domain/repository/ScrapJpaRepository.java
src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/repositoryImpl/ScrapQueryRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/repositoryImpl/ScrapRepositoryImpl.java
src/main/java/com/kakaotech/ott/ott/scrap/infrastructure/sycn/ScrapSyncServiceImpl.java
src/main/resources/application.properties

- 좋아요, 스크랩에 대한 객체 scrap_count, like_count 적용
- 스크랩은 type 별 구분

feat: 좋아요 및 스크랩 count 적용 및 타입 적용

---

src/main/java/com/kakaotech/ott/ott/global/config/RedisStreamConsumerConfig.java
src/main/java/com/kakaotech/ott/ott/global/config/RedissonConfig.java
src/main/resources/application-dev.properties
src/main/resources/application-feat.properties
src/main/resources/application-prod.properties
src/main/resources/application.properties

- Redisson-Sentinel 설정 properties 및 configuration 설정
- RedisStreamConsumerConfiguration에서 Scrap의 type, targetId 문자열 저장 순서 변경

feat: redisson-sentinel 설정 및 RedisStreamConsumerConfig 변경

---

src/main/java/com/kakaotech/ott/ott/productOrder/presentation/controller/ProductOrderController.java

feat: 주석 제거

---

src/main/resources/application.properties

fix: 변수명 변경
